name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ahincho/nova-devops/.github/workflows/reusable-build-gradle.yml@main
    secrets: inherit

  sonar:
    if: github.event_name == 'pull_request'
    uses: ahincho/nova-devops/.github/workflows/reusable-sonarcloud-gradle.yml@main
    with:
      sonar-org: ahincho
      sonar-project-key: ahincho_nova-starter
    secrets: inherit

  matrix:
    if: github.event_name == 'pull_request'
    uses: ahincho/nova-devops/.github/workflows/reusable-build-matrix.yml@main
    with:
      build-tool: gradle
    secrets: inherit

  owasp:
    if: github.event_name == 'pull_request'
    uses: ahincho/nova-devops/.github/workflows/reusable-owasp-check.yml@main
    with:
      build-tool: gradle
    secrets: inherit

  sbom:
    if: github.event_name == 'pull_request'
    uses: ahincho/nova-devops/.github/workflows/reusable-sbom.yml@main
    with:
      build-tool: gradle
    secrets: inherit